# Generated by Django 5.0.6 on 2024-05-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('mesto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('pozice', models.CharField(max_length=50)),
                ('cislo_dresu', models.PositiveIntegerField()),
                ('tym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotbal.tym')),
            ],
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
                ('domaci_skore', models.PositiveIntegerField()),
                ('hostujici_skore', models.PositiveIntegerField()),
                ('domaci_tym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaci_tymy', to='fotbal.tym')),
                ('hostujici_tym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostujici_tymy', to='fotbal.tym')),
            ],
        ),
    ]
